version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bookstore-postgres
    environment:
      POSTGRES_DB: bookstore_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: bookstore-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8081:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    restart: unless-stopped

  bookstore-api:
    image: ghcr.io/alitarek3102005/bookstore:latest
    container_name: bookstore-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - keycloak
    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookstore_db
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/bookstore-realm
      KEYCLOAK_ADMIN_SERVER_URL: http://keycloak:8080
    restart: unless-stopped

volumes:
  postgres_data:
  keycloak_data: