
spring:
  application:
    name: BookStore

  datasource:
    url: jdbc:postgresql://localhost:5433/bookstore_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin_password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: "0"
    locations: classpath:migration
    url: jdbc:postgresql://localhost:5433/bookstore_db
    user: admin
    password: admin_password

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/bookstore-realm

keycloak:
  admin:
    server-url: http://localhost:8081
    realm: bookstore-realm
    client-id: bookstore-admin-client
    client-secret: ZIqNbC4yhf6lYGanV7TFHBcBfo7OYUM1